### ISSUE TITLE
Recipe Not showing on JEI

### ISSUE THREAD

**Issue by Jadan1213** [2mal3/Chunk-Loader#22]
### Minecraft version

1.20.1

### Datapack version

3.0.1

### Expected Behavior

Recipe should show and be available in JEI

### Actual Behavior

Even though the release notes on the MODRINTH version 3.0.1 show that this should be fixed, it does not show in JEI for crafting.

### Reproduction Steps

Load MODRINTH v3.0.1 and open JEI. recipe is not shown, and searching for chunk show's no available recipe for the chunk loader.

**Comment by 2mal3** [comment]
Should now be fixed in v3.0.2
